<#macro emailLayout>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--[if mso]><noscript><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml></noscript><![endif]-->
</head>
<body style="margin:0;padding:0;background-color:#f1f5f9;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;-webkit-font-smoothing:antialiased;">
    <div style="padding:40px 16px;">
        <div style="max-width:560px;margin:0 auto;">

            <!-- HEADER -->
            <div style="background-color:#0f172a;padding:32px 40px;border-radius:16px 16px 0 0;text-align:center;">
                <table role="presentation" cellpadding="0" cellspacing="0" style="margin:0 auto;">
                    <tr>
                        <td style="vertical-align:middle;padding-right:10px;">
                            <img src="https://forest-manager.eu/icon-192.png" alt="" width="32" height="32" style="display:block;border:0;border-radius:8px;" />
                        </td>
                        <td style="vertical-align:middle;">
                            <span style="font-size:22px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;">Forest</span><span style="font-size:22px;font-weight:700;color:#4ade80;letter-spacing:-0.3px;">Manager</span>
                        </td>
                    </tr>
                </table>
            </div>

            <!-- CONTENT -->
            <div style="background-color:#ffffff;padding:40px 40px 32px;color:#1e293b;line-height:1.7;font-size:15px;">
                <#nested>
            </div>

            <!-- FOOTER -->
            <div style="background-color:#f8fafc;padding:24px 40px;text-align:center;font-size:12px;color:#94a3b8;border-top:1px solid #e2e8f0;border-radius:0 0 16px 16px;line-height:1.6;">
                <p style="margin:0 0 4px;">&copy; ${.now?string('yyyy')} Forest Manager &middot; natureport UG</p>
                <p style="margin:0;color:#cbd5e1;">${msg("footerAutoGenerated")}</p>
            </div>

        </div>
    </div>
</body>
</html>
</#macro>
